import type {Metadata} from 'next'
import {Geist, Geist_Mono} from 'next/font/google'
import AppFooter from '@/components/layout/AppFooter'
import Providers from '@/lib/Providers'
import AppHeader from './components/layout/AppHeader'
import './globals.css'

const geistSans = Geist({
	variable: '--font-geist-sans',
	subsets: ['latin'],
})

const geistMono = Geist_Mono({
	variable: '--font-geist-mono',
	subsets: ['latin'],
})

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({children}: LayoutProps<'/'>) {
	return (
		<html
			lang="en"
			className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
		>
			<Providers>
				<body>
					{/* Базовый каркас высоты: пригодится дальше, когда появятся внутренние скроллы */}
					<div className="min-h-dvh flex flex-col">
						<AppHeader />
						<main className="flex-1 min-h-0">{children}</main>
						<AppFooter />
					</div>
				</body>
			</Providers>
		</html>
	)
}
