import type {Metadata} from 'next'
import localFont from 'next/font/local'
import AppFooter from '@/components/layout/AppFooter'
import Providers from '@/lib/Providers'
import AppHeader from './components/layout/AppHeader'
import './globals.css'

// Шрифты лежат локально: сборка не зависит от доступа к Google Fonts
const geistSans = localFont({
	src: './fonts/geist-latin.woff2',
	variable: '--font-geist-sans',
	weight: '100 900',
})

const geistMono = localFont({
	src: './fonts/geist-mono-latin.woff2',
	variable: '--font-geist-mono',
	weight: '100 900',
})

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({children}: LayoutProps<'/'>) {
	return (
		<html
			lang="en"
			className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
		>
			<Providers>
				<body>
					{/* Базовый каркас высоты: пригодится дальше, когда появятся внутренние скроллы */}
					<div className="min-h-dvh flex flex-col">
						<AppHeader />
						<main className="flex-1 min-h-0">{children}</main>
						<AppFooter />
					</div>
				</body>
			</Providers>
		</html>
	)
}
